### ISSUE TITLE
你好，大佬能帮忙看下么, 我移植了 你这个功能 但是好像是除bug了

### ISSUE THREAD

**Issue by wang-yi-bit64** [liuye1296/react-keepAlive#1]
这是复现仓库： https://github.com/qianyeyixia/vite-react-js
切换和关闭别的都没问题 就是关闭首页会有问题

**Comment by liuye1296** [comment]
这个是 React18 跟  react-router 的问题。 要改两个地方
![image](https://user-images.githubusercontent.com/17822099/168556135-4f5546ac-ac1e-4bf4-bbc9-e0c55db8de44.png)
 晚点我更新一版React 18的

**Comment by liuye1296** [comment]
这个是最粗暴的方式。合理的可以看我最新的代码

**Comment by wang-yi-bit64** [comment]
> 这个是最粗暴的方式。合理的可以看我最新的代码

感谢指点

**Comment by wang-yi-bit64** [comment]
> 这个是 React18 跟 react-router 的问题。 要改两个地方 ![image](https://user-images.githubusercontent.com/17822099/168556135-4f5546ac-ac1e-4bf4-bbc9-e0c55db8de44.png) 晚点我更新一版React 18的
你好 我按照你写的重新更新了发现 剩下两个标签页得时候 有时候会出现 删不掉得情况, 感觉是在删除的一瞬间就有添加了一个，我没有定位到问题所在，但是我看的你写的没有这个问题

**Comment by wang-yi-bit64** [comment]
> > 这个是 React18 跟 react-router 的问题。 要改两个地方 ![image](https://user-images.githubusercontent.com/17822099/168556135-4f5546ac-ac1e-4bf4-bbc9-e0c55db8de44.png) 晚点我更新一版React 18的
> > 你好 我按照你写的重新更新了发现 剩下两个标签页得时候 有时候会出现 删不掉得情况, 感觉是在删除的一瞬间就有添加了一个，我没有定位到问题所在，但是我看的你写的没有这个问题

突然好了
