### ISSUE TITLE
maxLen这个配置好像没有效果

### ISSUE THREAD

**Issue by thomas-void0** [liuye1296/react-keepAlive#3]
如下所示：虽然传了maxLen,但是在添加的时候是直接默认取的10这个字面量。
![image](https://user-images.githubusercontent.com/48620706/200764783-3b638036-a035-4d32-b959-7c599dece61c.png)

**Comment by liuye1296** [comment]
是的  在reducer 里面我写死的10。目前还没想好 怎么两个地方公用一个maxLen，后续在考考虑

**Comment by liuye1296** [comment]
目前来说 要想实现这种 有两个方式（我能想到的），
1：如果 maxLen是一个常量  那就提取出一个公有常量就行  这种方式适用 项目中（不是框架通用的方式）
2：使用useContext 抽象出一个全局的配置类似（ant  ConfigProvider组件）， 这种符合React 的做法 但是我感觉太麻烦了  一个小需求 引入一个额外的全局配置组件 
PS： 我们公司的项目我是用第一种
