### ISSUE TITLE
请问你这个结构权限怎么对接的？

### ISSUE THREAD

**Issue by wang-yi-bit64** [liuye1296/react-keepAlive#4]
是渲染菜单的时候控制么？ 还是直接根据权限生成路由表呢？ 能说下思路参考下 非常感谢

**Comment by liuye1296** [comment]
![image](https://user-images.githubusercontent.com/17822099/207832207-37091ec9-0416-4a70-8289-9253d3a44454.png)

**Comment by liuye1296** [comment]
那个 获取后端的菜单 最好放在状态库里面  不要每次请求 只做一次请求

**Comment by liuye1296** [comment]
RouteConfig  特意有个 name熟悉 他就是仿Vue  用Name 做唯一值，然后后端也是维护这个Name 作为唯一ID 的菜单
 通过 角色选菜单 用户选角色, 查询用户下所有的菜单 用name做接口　跟本地的路由tree  diff

**Comment by liuye1296** [comment]
RouteConfig 特意有个 name属性 他就是仿Vue 用Name 做唯一值，然后后端也是维护这个Name 作为唯一ID 的菜单
通过 角色选菜单 用户选角色, 查询用户下所有的菜单 用name做接口　跟本地的路由tree diff

**Comment by qianyeyixia** [comment]
非常感谢

**Comment by wang-yi-bit64** [comment]
> RouteConfig 特意有个 name属性 他就是仿Vue 用Name 做唯一值，然后后端也是维护这个Name 作为唯一ID 的菜单 通过 角色选菜单 用户选角色, 查询用户下所有的菜单 用name做接口　跟本地的路由tree diff

非常感谢

**Comment by wang-yi-bit64** [comment]
感谢 已经对接完成了
